name: Cross-Platform Build

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch

jobs:

  # Windows Build (MSVC)
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-clang
            make

      - name: Build for Windows
        shell: msys2 {0}
        run: |
          cd src
          g++ -O3 -lm -fopenmp AGM_sfunctions.cpp fileutils.cpp stringutils.cpp paramfile.cpp fluctuoscope.cpp -c
          g++ main.cpp fluctuoscope.o  AGM_sfunctions.o fileutils.o stringutils.o paramfile.o -O3 -lm -fopenmp -o ../FSCOPE_windows.exe
          g++ -O3 -lm -fopenmp -shared -o ../fluctuoscopy_extC.dll -fPIC AGM_sfunctions.cpp fileutils.cpp stringutils.cpp paramfile.cpp fluctuoscope.cpp

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            fluctuoscopy_extC.dll
            FSCOPE_windows.exe

  # Linux Build (Ubuntu)
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up GCC and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ clang libomp-dev

      - name: Build for Linux
        run: |
          cd src
          g++ -O3 -lm -fopenmp AGM_sfunctions.cpp fileutils.cpp stringutils.cpp paramfile.cpp fluctuoscope.cpp -c
          g++ main.cpp fluctuoscope.o  AGM_sfunctions.o fileutils.o stringutils.o paramfile.o -O3 -lm -fopenmp -o ../FSCOPE_linux
          g++ -O3 -lm -fopenmp -shared -o ../fluctuoscopy_extC.so -fPIC AGM_sfunctions.cpp fileutils.cpp stringutils.cpp paramfile.cpp fluctuoscope.cpp

      - name: Upload Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            fluctuoscopy_extC.so
            FSCOPE_linux

  # maxOS (x86) Build
  macos-x86:
    runs-on: macos-13
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Set up Homebrew and dependencies
        run: |
          brew install llvm libomp
          echo "LLVM_PATH=$(brew --prefix llvm)" >> $GITHUB_ENV
          echo "export PATH=$(brew --prefix llvm)/bin:$PATH" >> $GITHUB_ENV
          echo "export LDFLAGS=-L$(brew --prefix llvm)/lib" >> $GITHUB_ENV
          echo "export CPPFLAGS=-I$(brew --prefix llvm)/include -I$(brew --prefix libomp)/include" >> $GITHUB_ENV
          echo "export CC=$(brew --prefix llvm)/bin/clang" >> $GITHUB_ENV
          echo "export CXX=$(brew --prefix llvm)/bin/clang++" >> $GITHUB_ENV
    
      - name: Build for macOS (x86)
        run: |
          cd src
            $(brew --prefix llvm)/bin/clang++ -O3 -lm -Xpreprocessor -fopenmp \
                -I$(brew --prefix llvm)/include -L$(brew --prefix llvm)/lib -lomp \
                -arch x86_64 -c AGM_sfunctions.cpp fileutils.cpp stringutils.cpp paramfile.cpp fluctuoscope.cpp
            $(brew --prefix llvm)/bin/clang++ main.cpp fluctuoscope.o AGM_sfunctions.o fileutils.o stringutils.o paramfile.o \
                -O3 -lm -Xpreprocessor -fopenmp -I$(brew --prefix llvm)/include -L$(brew --prefix llvm)/lib -lomp -arch x86_64 \
                -o ../FSCOPE_mac_x86
            $(brew --prefix llvm)/bin/clang++ -O3 -lm -Xpreprocessor -fopenmp \
                -shared -I$(brew --prefix llvm)/include -L$(brew --prefix llvm)/lib -lomp \
                -arch x86_64 -o ../fluctuoscopy_extC_x86.dylib -fPIC AGM_sfunctions.cpp fileutils.cpp stringutils.cpp paramfile.cpp fluctuoscope.cpp
    
      - name: Upload macOS (x86) Build
        uses: actions/upload-artifact@v4
        with:
          name: macos-x86-build
          path: |
            fluctuoscopy_extC_x86.dylib
            FSCOPE_mac_x86

  # macOS (arm64) Build
  macos-arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Homebrew and dependencies
        run: |
          brew install llvm libomp

          echo "LLVM_PATH=$(brew --prefix llvm)" >> $GITHUB_ENV
          echo "export PATH=$(brew --prefix llvm)/bin:$PATH" >> $GITHUB_ENV
          echo "export LDFLAGS=-L$(brew --prefix llvm)/lib" >> $GITHUB_ENV
          echo "export CPPFLAGS=-I$(brew --prefix llvm)/include -I$(brew --prefix libomp)/include" >> $GITHUB_ENV
          echo "export CC=$(brew --prefix llvm)/bin/clang" >> $GITHUB_ENV
          echo "export CXX=$(brew --prefix llvm)/bin/clang++" >> $GITHUB_ENV

      - name: Build for macOS arm64
        run: |
          cd src
          $(brew --prefix llvm)/bin/clang++ -O3 -lm -Xpreprocessor -fopenmp \
            -I$(brew --prefix llvm)/include -L$(brew --prefix llvm)/lib -lomp \
            -arch arm64 -c AGM_sfunctions.cpp fileutils.cpp stringutils.cpp paramfile.cpp fluctuoscope.cpp
          $(brew --prefix llvm)/bin/clang++ main.cpp fluctuoscope.o AGM_sfunctions.o fileutils.o stringutils.o paramfile.o \
            -O3 -lm -Xpreprocessor -fopenmp -I$(brew --prefix llvm)/include -L$(brew --prefix llvm)/lib -lomp -arch arm64 \
            -o ../FSCOPE_mac_arm64
          $(brew --prefix llvm)/bin/clang++ -O3 -lm -Xpreprocessor -fopenmp \
            -shared -I$(brew --prefix llvm)/include -L$(brew --prefix llvm)/lib -lomp \
            -arch arm64 -o ../fluctuoscopy_extC_arm64.dylib -fPIC AGM_sfunctions.cpp fileutils.cpp stringutils.cpp paramfile.cpp fluctuoscope.cpp

        # upload to artifacts
      - name: Upload macOS arm64 Build
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-build
          path: |
            fluctuoscopy_extC_arm64.dylib
            FSCOPE_mac_arm64

  combine-macos:
    runs-on: macos-latest
    needs: [macos-x86, macos-arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download macOS x86 Build
        uses: actions/download-artifact@v4
        with:
          name: macos-x86-build
          path: .

      - name: Download macOS arm64 Build
        uses: actions/download-artifact@v4
        with:
          name: macos-arm64-build
          path: .

      - name: Combine into Universal Binary
        run: |
          lipo -create fluctuoscopy_extC_x86.dylib fluctuoscopy_extC_arm64.dylib -output fluctuoscopy_extC.dylib
          lipo -create FSCOPE_mac_x86 FSCOPE_mac_arm64 -output FSCOPE_mac

      - name: Upload macOS Universal Binary
        uses: actions/upload-artifact@v4
        with:
          name: macos-universal-build
          path: |
            fluctuoscopy_extC.dylib
            FSCOPE_mac
